In [1]:
import pandas as pd
import os

In [ ]:
os.makedirs('data/processed', exist_ok=True)

#Cleanning the data "Nav_history.CSV"

In [7]:
# 1. Load the data
df_nav = pd.read_csv(r'C:\Users\TEJ\OneDrive\Desktop\Project\Data Cleaning + SQL Database Design\Datasets\02_nav_history.csv')
df_nav

       amfi_code        date       nav
0         119551  2022-01-03   54.3856
1         119551  2022-01-04   54.3474
2         119551  2022-01-05   54.6869
3         119551  2022-01-06   55.4550
4         119551  2022-01-07   55.3692
...          ...         ...       ...
45995     149324  2026-05-25  292.4810
45996     149324  2026-05-26  291.2707
45997     149324  2026-05-27  288.8007
45998     149324  2026-05-28  280.6873
45999     149324  2026-05-29  279.7511

[46000 rows x 3 columns]

In [9]:
# 2. Format Dates
df_nav['date'] = pd.to_datetime(df_nav['date'])
df_nav['date']

0       2022-01-03
1       2022-01-04
2       2022-01-05
3       2022-01-06
4       2022-01-07
           ...
45995   2026-05-25
45996   2026-05-26
45997   2026-05-27
45998   2026-05-28
45999   2026-05-29
Name: date, Length: 46000, dtype: datetime64[us]

In [11]:
# 3. Sort the data
df_nav = df_nav.sort_values(['amfi_code', 'date'])
df_nav

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [12]:
# 4. Impute Missing Values (Forward-fill by amfi_code)
df_nav['nav'] = df_nav.groupby('amfi_code')['nav'].ffill()
df_nav

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [13]:
# 5. Duplicate value removal
df_nav = df_nav.drop_duplicates()
df_nav

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [14]:
# 6. Validate (Ensure all NAV > 0)
df_nav = df_nav[df_nav['nav'] > 0]
df_nav

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [15]:
print(f"Cleaned NAV History shape: {df_nav.shape}")

Cleaned NAV History shape: (46000, 3)

#CLEANING INVESTOR-TRANSACTIONS CSV

In [17]:
# 1. Load the data
df_trans = pd.read_csv(r'C:\Users\TEJ\OneDrive\Desktop\Project\Data Cleaning + SQL Database Design\Datasets\08_investor_transactions.csv')
df_trans

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [18]:
# 2. Standardize Types (Strips whitespace and Capitalizes the first letter)
df_trans['transaction_type'] = df_trans['transaction_type'].astype(str).str.strip().str.title()
df_trans

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,Sip,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,Sip,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,Sip,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,Sip,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,Sip,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,Sip,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [20]:
# 3. Validate Amounts
df_trans = df_trans[df_trans['amount_inr'] > 0]
df_trans

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,Sip,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,Sip,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,Sip,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,Sip,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,Sip,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,Sip,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [22]:
# 4. Format Dates
df_trans['transaction_date'] = pd.to_datetime(df_trans['transaction_date'])
df_trans['transaction_date']

0       2024-01-01
1       2024-01-01
2       2024-01-01
3       2024-01-01
4       2024-01-01
           ...
32773   2025-05-30
32774   2025-05-30
32775   2025-05-30
32776   2025-05-30
32777   2025-05-30
Name: transaction_date, Length: 32778, dtype: datetime64[us]

In [24]:
# 5. Verify KYC Status
allowed_kyc = ['Verified', 'Pending', 'Rejected']
df_trans = df_trans[df_trans['kyc_status'].isin(allowed_kyc)]
df_trans

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,Sip,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,Sip,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,Sip,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,Sip,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,Sip,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,Sip,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [25]:
print(f"Cleaned Transactions shape: {df_trans.shape}")

Cleaned Transactions shape: (32778, 13)

#CLEANING SCHEME-PERFORMANCE CSV

In [27]:
# 1. Load the data
df_perf = pd.read_csv(r'C:\Users\TEJ\OneDrive\Desktop\Project\Data Cleaning + SQL Database Design\Datasets\07_scheme_performance.csv')
df_perf.head(5)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [31]:
# 2. Numeric Validation
# Replace 'return_1y', 'return_3y', etc., with your actual column names
return_columns = ['return_1y', 'return_3y', 'return_5y'] 

for col in return_columns:
    if col in df_perf.columns:
        df_perf[col] = pd.to_numeric(df_perf[col], errors='coerce')

# Drop rows where any of the return columns became NaN due to coercion
existing_cols = [col for col in return_columns if col in df_perf.columns]
df_perf = df_perf.dropna(subset=existing_cols)

df_perf.head(6)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low
5,100016,HDFC Top 100 Fund - Regular Plan - Growth,HDFC Mutual Fund,Large Cap,Regular,10.94,14.84,11.32,14.06,0.78,0.97,1.06,1.70,14.0,-17.41,6434,1.55,5,Moderate

In [33]:
# 3. Expense Ratio Check
df_perf = df_perf[(df_perf['expense_ratio_pct'] >= 0.1) & (df_perf['expense_ratio_pct'] <= 2.5)]
df_perf.head(6)
print(f"Cleaned Performance shape: {df_perf.shape}")

Cleaned Performance shape: (40, 19)